apiVersion: apps/v1
kind: Deployment

metadata:
  name: storage-test-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: storage-test

  template:
    metadata:
      labels:
        app: storage-test

    spec:
      containers:
        - name: nginx
          image: nginx

          volumeMounts:
            - name: data
              mountPath: /data

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dynamic-pvc   # Connect Deployment Pods to the PVC
