apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: myapp    #selects the Pods with label app=myapp. This is how the Service knows which Pods to send traffic to.
  type: NodePort   #nodePort service type exposes the service on each Node's IP at a static port (the NodePort). A ClusterIP service, to which the NodePort service routes, is automatically created. You’ll be able to contact the NodePort service, from outside the cluster, by requesting <NodeIP>:<NodePort>.
  ports:
  - port: 4000
    targetPort: 80
    nodePort: 30500 #used when you use service type as NodePort or LoadBalancer. The port on each node on which this service is exposed when type is NodePort or LoadBalancer. If not specified, a port will be automatically allocated from the range 30000-32767. If specified, it will be allocated to the service if unused or else creation of the service will fail with an error. This field will be wiped when updating a Service to type=ExternalName, which makes this field irrelevant.