apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: my-replica-set
  labels:
    app: myapp                 # Label of the ReplicaSet itself

spec:
  replicas: 3

  selector:
    matchLabels:
      app: myapp               # Find Pods having app=myapp

  template:
    metadata:
      labels:
        app: myapp             # Label that will be given to every Pod

    spec:
      containers:
        - name: myapp
          image: nginx:latest
          ports:
            - containerPort: 80